# Generated by Django 3.0.5 on 2020-04-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expanse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpanseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expanse_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expanse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('usd', '$'), ('uzs', 'uzs'), ('rub', 'rub')], default='usd', max_length=5)),
                ('type', models.ForeignKey(default=expanse.models.get_def, on_delete=models.SET(expanse.models.set_deleted_expanse_type), to='expanse.ExpanseType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
