# Generated by Django 3.0.5 on 2020-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expanse', '0003_auto_20200416_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expansetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
