# Generated by Django 3.0.5 on 2020-04-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_expanse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='user',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17),
        ),
    ]
